sonar.projectKey=multimedia-gallery-steganography-detection
sonar.projectName=Multimedia Gallery - Steganography Detection
sonar.projectVersion=1.0
sonar.sources=src/main/java,frontend/src
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.jacoco.reportPaths=target/jacoco.exec
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.java.coveragePlugin=jacoco
sonar.host.url=http://localhost:9000
sonar.login=admin
sonar.password=admin
sonar.exclusions=**/dto/**,**/config/**
sonar.sourceEncoding=UTF-8
